# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # General Vagrant VM configuration.
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.linked_clone = true
  end

  # application server
  config.vm.define "app" do |app|
    app.vm.box = "generic/freebsd13"
    app.vm.hostname = "app.test"
    app.vm.network :private_network, ip: "192.168.60.50"
  end

end
